apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  ports:
  - name: wyoming 
    port: 10300
    targetPort: 10300