{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
{{ . | toYaml | indent 4 }}
  {{- end }}
spec:
  selector:
    app: {{ .Chart.Name }}-{{ .Release.Name }}
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
  - name: openvpn
    port: {{ .Values.service.port }}
    targetPort: 1194
    protocol: {{ .Values.config.protocol | upper | quote }}
{{- end }}
