repository: sebd/openvpn

persistence:
  enabled: true
  # storageClassName: nfs-client

ca:
  bootstrap: true 
  serverName: example.net

service:
  enabled: true
  type: NodePort
  port: "1194"

tolerations: {}
nodeSelector: {}


config:
  protocol: tcp # or udp
  host: vpn.example.com

