apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-k8s.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "paperless-k8s.name" . }}
    helm.sh/chart: {{ include "paperless-k8s.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "paperless-k8s.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
