apiVersion: v1
# renovate: depName: vaultwarden/server datasource: docker
appVersion: "1.27.0-alpine"
description: A Bitwarden Helm chart for Kubernetes
name: bitwarden-k8s
version: 0.1.10
icon: https://raw.githubusercontent.com/bitwarden/brand/master/icons/icon.svg
sources:
  - https://github.com/dani-garcia/bitwarden_rs
  - https://github.com/cdwv/bitwarden-k8s
maintainers:
  - name: CodeWave
    email: hello@codewave.eu
    url: https://codewave.eu
