apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ha-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.org/websocket-services: "home-assistant-ws"
spec:
  rules:
    - host: ha.bks.rshc.de
      http:
        paths:
        - path: /api/websocket
          pathType: Prefix
          backend:
            service:
              name: home-assistant-ws
              port: 
                number: 8123
        - path: /
          pathType: Prefix
          backend:
            service:
              name: home-assistant
              port: 
                number: 8123
