apiVersion: v1
kind: Service
metadata:
  name: home-assistant-ws
spec:
  selector:
    app: home-assistant
  ports:
  - name: ws
    port: 8123
    targetPort: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  labels:
    app: home-assistant
spec:
  selector:
    app: home-assistant
  ports:
  - name: http
    port: 8123
    targetPort: 8123
  - name: callback
    port: 8040
    targetPort: 8040
---
apiVersion: v1
kind: Service
metadata:
  name: ha-lb
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.241
  selector:
    app: home-assistant
  ports:
  - name: http-ha
    port: 8123
    targetPort: 8123
  - name: hue
    port: 80
    targetPort: 8300